import listening from "../assets/images/skills/skills-listening.png";
import grammar from "../assets/images/skills/skills-grammar.png";
import reading from "../assets/images/skills/skills-reading.png";

export const skillsList = [
    {
        id: 1,
        img: grammar,
        title: "Grammar",
        text: "One of the most important and extensive areas of natural science, the science that studies substances, also their composition ",
    },
    {
        id: 2,
        img: reading,
        title: "Reading",
        text: "perception and response actions of the user resulting from the use and/or upcoming use of the product, system or service",
    },
    {
        id: 3,
        img: listening,
        title: "Listening",
        text: "Here you can find activities to practise your listening skills. Listening will help you to improve your understanding ",
    },
];

export const AUDIOS_URL =
    "https://6254687719bc53e2347e0da5.mockapi.io/Listening";

export const READING_URL =
    "https://6254687719bc53e2347e0da5.mockapi.io/Reading";

export const translatedWords = {
    when: "когда",
    an: "вышеуказанный",
    official: "официальный",
    of: "из",
    a: "а",
    government: "правительство",
    or: "или",
    business: "бизнес",
    is: "является",
    acting: "играет роль",
    dishonestly: "нечестно",
    we: "мы",
    say: "сказать",
    that: "тот",
    this: "этот",
    person: "персона",
    corrupt: "коррумпированный",
    corruption: "коррупция",
    serious: "серьезно",
    problem: "проблема",
    in: "в",
    many: "многие",
    countries: "страны",
    around: "вокруг",
    the: "в",
    world: "земля",
    there: "там",
    are: "находятся",
    several: "несколько",
    different: "другой",
    kinds: "виды",
    practices: "практики",
    including: "в том числе",
    bribes: "взятки",
    kickbacks: "откаты",
    nepotism: "кумовство",
    and: "и",
    embezzlement: "растрата",
    bribe: "взятка",
    payment: "оплата",
    money: "деньги",
    some: "некоторый",
    other: "Другие",
    benefit: "преимущества",
    exchange: "обмен",
    for: "для",
    decision: "решение",
    would: "бы",
    not: "не",
    otherwise: "в противном случае",
    be: "быть",
    made: "сделан",
    example: "пример",
    accused: "обвиняемый",
    criminal: "преступник",
    might: "мощь",
    judge: "судить",
    so: "так",
    make: "делать",
    guilty: "виновный",
    another: "другой",
    owner: "владелец",
    allow: "позволять",
    construction: "строительство",
    very: "очень",
    unsafe: "незащищенный",
    buildings: "постройки",
    kickback: "откат",
    similar: "такой же / одинаковый",
    to: "к",
    except: "кроме",
    receives: "получает",
    part: "часть",
    dishonest: "нечестный",
    deal: "по рукам",
    governments: "правительства",
    sometimes: "иногда",
    decide: "принять решение",
    which: "который",
    company: "компания",
    should: "должен",
    build: "строить",
    road: "дорога",
    offer: "сделка",
    who: "кто",
    makes: "делает",
    will: "будем",
    chosen: "выбранный",
    even: "даже",
    if: "если",
    it: "это",
    best: "лучший",
    job: "работа",
};

export const presentSimple = [
    {
        id: 1,
        text: "I .... Spanish with my sister.",
        answer1: "study",
        answer2: "studies",
    },
    {
        id: 2,
        text: "My sister .... a shower every morning.",
        answer1: "take",
        answer2: "takes",
    },
    {
        id: 3,
        text: "This house .... to my grandmother.",
        answer1: "belong",
        answer2: "belongs",
    },
    {
        id: 4,
        text: "We .... to go for a walk in the morning.",
        answer1: "like",
        answer2: "likes",
    },
    {
        id: 5,
        text: "My husband and I .... a lot of money on books.",
        answer1: "spend",
        answer2: "spends",
    },
];

export const rightAnswers = ["study", "takes", "belongs", "like", "spend"];
